### ISSUE TITLE
Global CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by arifintajul4** [tiavina-mika/mui-tiptap-editor#72]
<img width="990" alt="Screenshot 2024-10-21 at 15 02 12" src="https://github.com/user-attachments/assets/a38c556b-20e4-48ba-9980-17639887f6c7">
Problem with nextjs 13

Reference: https://nextjs.org/docs/messages/css-npm

**Comment by tiavina-mika** [comment]
Fixed and tested with Next.js 14 and 15.
Here's an [example ](https://github.com/tiavina-mika/mui-tiptap-editor-nextjs)using Next.js 15
