### ISSUE TITLE
Quick feedback after your last update

### ISSUE THREAD

**Issue by akreienbring** [tiavina-mika/mui-tiptap-editor#87]
Thanks for your last commit! Great tool!

However, I noticed that you mention 'code' as a toolbar option in your docs, but it's not implemented.
In your Toolbar.tsx you could add:
```
{
  name: 'code',
  icon: Code,
  onClick: () => editor.chain().focus().toggleCode().run(),
  disabled: false,
  split: true,
  tooltip: toolbarLabels?.code || 'Code',
},

```
and add the tiptap extension: @tiptap/extension-code

Nice to have: 

- An option to disable the preview and/or the Tabs at the top at all
- An option to have the toolbar on top

Anyway, thanks for your work! :-)

**Comment by tiavina-mika** [comment]
All done. Thank you for your suggestions. 
Please upgrade to the latest version of `mui-tiptap-editor`
